---
title: Kappel Investments - Análise da eficiência energética de geradoras solares
  compartilhadas do estado de São Paulo por séries temporais (NAVI Tech Journey)
output: rmarkdown::github_document
---

```{r message=FALSE, warning=FALSE}
#Importação de bibliotecas
library(readr)
library(dplyr)
library(tidyverse)
library(lubridate)
library(forecast)
library(fields)

#Importação do banco de dados da ONS (Fator de Capacidade 2022)
FATOR_CAPACIDADE_2022 <- read_delim("/Users/haddad/Downloads/FATOR_CAPACIDADE_2022.csv", 
                                    delim = ";", escape_double = FALSE, trim_ws = TRUE)

#Criação de um subset que contém somente os dados do estado de São Paulo
FATOR_SP_2022 <- subset(FATOR_CAPACIDADE_2022, FATOR_CAPACIDADE_2022$id_estado == "SP")

#Atualização do subset para conter somente os dados de energia solar
FATOR_SP_2022 <- subset(FATOR_SP_2022, FATOR_SP_2022$nom_tipousina == "Solar")

#Eliminação das categorias desnecessárias à análise de dados
FATOR_SP_2022$id_subsistema <- NULL
FATOR_SP_2022$nom_subsistema <- NULL
FATOR_SP_2022$id_estado <- NULL
FATOR_SP_2022$nom_estado <- NULL
FATOR_SP_2022$nom_localizacao <- NULL
FATOR_SP_2022$val_latitude <- NULL
FATOR_SP_2022$val_longitude <- NULL
FATOR_SP_2022$nom_modalidadeoperacao <- NULL
FATOR_SP_2022$nom_tipousina <- NULL
FATOR_SP_2022$nom_usina_conjunto <- NULL

#Mudança de nomenclatura das categorias
names(FATOR_SP_2022)[1] <- 'nome'
names(FATOR_SP_2022)[2] <- 'data'
names(FATOR_SP_2022)[3] <- 'producao'
names(FATOR_SP_2022)[4] <- 'capacidade'
names(FATOR_SP_2022)[5] <- 'fator_capacidade'

#Preparação e correção de dados inconsistentes (ajuste do fator para o intervalo de 0 a 1)
FATOR_SP_2022$fator_capacidade <- as.numeric(FATOR_SP_2022$producao)/as.numeric(FATOR_SP_2022$capacidade)

#Criação de um dataset com os fatores condensados por dia (o fator do dia é a soma da energia
#produzida dividida pela soma das capacidades diárias das 4 usinas)
time_series <- FATOR_SP_2022 %>% group_by(data) %>% summarise(fator_capacidade = sum(producao))
time_series$fator_capacidade <- (time_series$fator_capacidade/(13911.36))

#Normalização dos fatores de capacidade (Min-Max Scaling)
max <- max(time_series$fator_capacidade)
min <- min(time_series$fator_capacidade)
time_series$fator_capacidade <- (time_series$fator_capacidade - min)/(max - min)

#Previsão da série temporal pelo método de Holt
ts <- ts(time_series$fator_capacidade)
previsao = holt(ts, damped = T, type = "multiplicative")
forecast::autoplot(previsao, series = "Conjunto de Teste")+
  ylab("Fator de capacidade das geradoras solares")+
  xlab("Tempo")

#Cálculo do valor médio e do desvio padrão do conjunto de dados
#(utilizado para mensurar a área necessária para aluguel por parte do cliente em função do seu
#consumo médio)
mean(time_series$fator_capacidade)
```

```{r}
#Com a análise da série temporal, pode-se realizar previsões de através de modelos estatísticos,as
#quais auxiliam o cliente a mensurar sua expectativa de geração de energia renovável para o mês
#seguinte. Caso a produção tenha uma expectativa de queda, espera-se um comportamente mais
#econômico por parte do cliente, o qual evitaria a necessidade de consumo de energia do mercado
#regulado/distribuidoras padrões.
```
